[app]
title = 二维码扫描器
package.name = qrscanner
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf,ttc
template.dir = 
version = 1.0
requirements = python3,kivy,opencv-python,pyzbar,Pillow,numpy,pyjnius
orientation = portrait
fullscreen = 0
android.permissions = CAMERA,INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
android.api = 33
android.minapi = 21
android.sdk = 33
android.ndk = 25b
android.private_storage = True
android.ndk_path = 
android.sdk_path = 
android.ant_path = 
android.skip_update = False
android.accept_sdk_license = True
android.entrypoint = org.kivy.android.PythonActivity
android.add_jars = 
android.add_aars = 
android.add_activities = 
android.add_services = 
android.whitelist = 
android.blacklist = 
android.whitelist_src = 
android.blacklist_src = 
android.add_src = 
android.add_jar = 
android.add_aar = 
android.gradle_dependencies = 
android.add_gradle_repositories = 
android.packaging_options = 
android.meta_data = 
android.library_repositories = 
android.include_extras = 
android.arch = armeabi-v7a
android.allow_backup = True
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0
ios.codesign.allowed = false
[buildozer]
log_level = 2
warn_on_root = 1
